on:
  push:
    branches:
      - "develop"
jobs:
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/flakehub-push@c51423e4c8d56e31a04fb8bae6da55b6b1c125ff
        with:
          visibility: "public"
          rolling: true
